BACKGROUND: str = "#FFFFFF"
COLOR: str = "#4D17E5"
HIGHLIGHT_COLOR = BACKGROUND # "#CAE85D"
MOVE_COLOR: str = "#CC339F"
UNDO_COLOR: str = "#A6A2B6"
LINE_WIDTH: int = 2

WIDTH: int = 800
HEIGHT: int = 600
NUM_ROWS: int = 40
NUM_COLS: int = 40
CELL_WIDTH: int = (WIDTH-10) // NUM_COLS
CELL_HEIGHT: int = (HEIGHT-20) // NUM_ROWS
