BACKGROUND: str = "#FFFFFF"
COLOR: str = "#4D17E5"
HIGHLIGHT_COLOR = BACKGROUND # "#CAE85D"
MOVE_COLOR: str = "#CC339F"
UNDO_COLOR: str = "#A6A2B6"
LINE_WIDTH: int = 2

CELL_WIDTH: int = 32
CELL_HEIGHT: int = 32
